// src/app/layout.tsx
"use client";
import "@/app/globals.css";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

const NoSSRSessionProvider = dynamic(
  () => import("@/components/ClientSessionProvider"),
  { ssr: false }
);

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <NoSSRSessionProvider>{children}</NoSSRSessionProvider>;
}
